name: Notify Telegram on Push to Main

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Telegram
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="📦 Có *push mới* vào nhánh *main* bởi *${{ github.actor }}* 🧠\n🗂 Repo: `${{ github.repository }}`\n🔗 Xem chi tiết: https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
